name: Bandit Security Analysis

on:
  push:
    branches:
      - main
      - akulka24
  pull_request:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install bandit

    - name: Run Bandit analysis
      run: |
        bandit -r hw2_debugging.py rand.py counting_sort.py > counting_sort_bandit_report.txt || true
        bandit -r hw2_debugging.py rand.py binary_search.py > binary_search_bandit_report.txt || true
        bandit -r hw2_debugging.py rand.py > bubble_sort_bandit_report.txt || true

    - name: Upload Bandit report (Counting Sort)
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report-counting_sort
        path: counting_sort_bandit_report.txt

    - name: Upload Bandit report (Binary Search)
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report-binary_search
        path: binary_search_bandit_report.txt

    - name: Upload Bandit report (Bubble Sort)
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report-bubble_sort
        path: bubble_sort_bandit_report.txt
