name: Pyflakes

on:
  push:
    branches:
      - main
      - akulka24
  pull_request:
    branches:
      - main

jobs:
  pyflakes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes

      - name: Run Pyflakes and Save Output
        run: |
          pyflakes hw2_debugging.py rand.py counting_sort.py > counting_sort_pyflakes_report.txt || true
          pyflakes hw2_debugging.py rand.py binary_search.py > binary_search_pyflakes_report.txt || true
          pyflakes hw2_debugging.py rand.py > bubble_sort_pyflakes_report.txt || true

      - name: Upload Pyflakes Report (Counting Sort)
        uses: actions/upload-artifact@v4
        with:
          name: pyflakes-report-counting_sort
          path: counting_sort_pyflakes_report.txt

      - name: Upload Pyflakes Report (Binary Search)
        uses: actions/upload-artifact@v4
        with:
          name: pyflakes-report-binary_search
          path: binary_search_pyflakes_report.txt

      - name: Upload Pyflakes Report (Bubble Sort)
        uses: actions/upload-artifact@v4
        with:
          name: pyflakes-report-bubble_sort
          path: bubble_sort_pyflakes_report.txt
