name: Pyflakes

on:
  push:
    branches:
      - main
      - akulka24
  pull_request:
    branches:
      - main

jobs:
  pyflakes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes

      - name: Run Pyflakes and Save Output
        run: |
          pyflakes hw2_debugging.py rand.py | tee pyflakes_report.txt || true

      - name: Upload Pyflakes Report
        uses: actions/upload-artifact@v4
        with:
          name: pyflakes-report
          path: pyflakes_report.txt
