name: Pylint

on:
  push:
    branches:
      - main
      - akulka24
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pylint and Save Output
        run: |
          pylint hw2_debugging.py rand.py counting_sort.py --output-format=colorized > counting_sort_pylint_report.txt || true
          pylint hw2_debugging.py rand.py binary_search.py --output-format=colorized > binary_search_pylint_report.txt || true
          pylint hw2_debugging.py rand.py --output-format=colorized > bubble_sort_pylint_report.txt || true

      - name: Upload Pylint Report (Counting Sort)
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report-counting_sort
          path: counting_sort_pylint_report.txt

      - name: Upload Pylint Report (Binary Search)
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report-binary_search
          path: binary_search_pylint_report.txt

      - name: Upload Pylint Report (Bubble Sort)
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report-bubble_sort
          path: bubble_sort_pylint_report.txt